# this one is just for the record
# i adjusted the program generated by my script and it turned out better than my manual attempts:

++++[->++++++<]>[>+++>++++>++<<<-]>.>+++++.+++++++..+++.>----.------------.<++++++++.--------.+++.------.--------.>+.
