# this one is generated by my script (ranged algo); no modifications
# prints "Hello(comma) world!"
# for now the algorithm is not optimal so it might not give result this good next time :/

# this initializes memory to | 0 _24_
++++[->++++++<]>

# this initializes ranges to | 0 0 _72_ 96 48 120
[->+++>++++>++>+++++<<<<]>

# start printing
.>+++++.+++++++..+++.>----.------------.>-.<<.+++.------.--------.>+.
